### ISSUE TITLE
Migrate to open-source destination

### ISSUE THREAD

**Issue by doublejosh** [Groucho/groucho#36]
This library will be moving into a new org namespace to transition into a tidier open-source location.

Namespace ideas:
- `knowanon`
- `semianon`
- `webgroucho`
- `zerostooges`
- ~~`groucho`~~
- ~~`grouchojs`~~
- ~~`p13n`~~
- `weow`
- `knowyou`
- `yeahnoiknow`
- `freals`

**Comment by trevorfox** [comment]
+1  for  `zerostooges` and `yeahnoiknow` for character

I like 'knowanon' but could be 'knowanon-kenobi' for more _character_ 

`weow` is fun to say but I don't know what it means

+1 for _tidy_ open source  :*|

**Comment by doublejosh** [comment]
MOVED!
